package io.github.tr100000.text_randomizer;

import dev.isxander.yacl3.api.ConfigCategory;
import dev.isxander.yacl3.api.Option;
import dev.isxander.yacl3.api.OptionDescription;
import dev.isxander.yacl3.api.OptionFlag;
import dev.isxander.yacl3.api.OptionGroup;
import dev.isxander.yacl3.api.YetAnotherConfigLib;
import dev.isxander.yacl3.api.controller.LongFieldControllerBuilder;
import dev.isxander.yacl3.api.controller.StringControllerBuilder;
import dev.isxander.yacl3.api.controller.TickBoxControllerBuilder;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.text.Text;

public final class ModYaclConfig {
    private ModYaclConfig() {}

    public static Screen generateScreen(Screen parent) {
        return YetAnotherConfigLib.createBuilder()
            .title(Text.literal("Text Randomizer Config"))
            .category(ConfigCategory.createBuilder()
                .name(Text.literal("Settings"))
                .option(Option.<Boolean>createBuilder()
                    .name(Text.literal("Mod Enabled"))
                    .binding(true, () -> ModConfig.INSTANCE.modEnabled, newValue -> ModConfig.INSTANCE.modEnabled = newValue)
                    .flag(OptionFlag.ASSET_RELOAD)
                    .controller(TickBoxControllerBuilder::create)
                    .build()
                )
                .group(OptionGroup.createBuilder()
                    .name(Text.literal("Text"))
                    .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Randomize Text"))
                        .binding(true, () -> ModConfig.INSTANCE.randomizeText, newValue -> ModConfig.INSTANCE.randomizeText = newValue)
                        .flag(OptionFlag.ASSET_RELOAD)
                        .controller(TickBoxControllerBuilder::create)
                        .build()
                    )
					.option(Option.<Boolean>createBuilder()
						.name(Text.literal("Ignore Empty Strings"))
						.binding(true, () -> ModConfig.INSTANCE.ignoreEmptyStrings, newValue -> ModConfig.INSTANCE.ignoreEmptyStrings = newValue)
						.flag(OptionFlag.ASSET_RELOAD)
						.description(OptionDescription.of(Text.literal("Ignore empty strings (disable for more chaos)")))
						.controller(TickBoxControllerBuilder::create)
						.build()
					)
                    .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Ignore Format Specifiers"))
                        .binding(false, () -> ModConfig.INSTANCE.ignoreFormatSpecifiers, newValue -> ModConfig.INSTANCE.ignoreFormatSpecifiers = newValue)
                        .flag(OptionFlag.ASSET_RELOAD)
                        .description(OptionDescription.of(Text.literal("Not recommended, enable if you hate yourself")))
                        .controller(TickBoxControllerBuilder::create)
                        .build()
                    )
                    .build()
                )
                .group(OptionGroup.createBuilder()
                    .name(Text.literal("Items"))
                    .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Randomize Item Models"))
                        .binding(false, () -> ModConfig.INSTANCE.randomizeItemModels, newValue -> ModConfig.INSTANCE.randomizeItemModels = newValue)
                        .flag(OptionFlag.ASSET_RELOAD)
                        .controller(TickBoxControllerBuilder::create)
                        .build()
                    )
                    .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Hide Item Ids"))
                        .binding(true, () -> ModConfig.INSTANCE.hideItemIds, newValue -> ModConfig.INSTANCE.hideItemIds = newValue)
                        .controller(TickBoxControllerBuilder::create)
                        .build()
                    )
                    .build()
                )
                .group(OptionGroup.createBuilder()
                    .name(Text.literal("Seed"))
                    .collapsed(true)
                    .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Use Seed"))
                        .binding(false, () -> ModConfig.INSTANCE.useSeed, newValue -> ModConfig.INSTANCE.useSeed = newValue)
                        .flag(OptionFlag.ASSET_RELOAD)
                        .controller(TickBoxControllerBuilder::create)
                        .build()
                    )
                    .option(Option.<Long>createBuilder()
                        .name(Text.literal("Seed"))
                        .binding(0L, () -> ModConfig.INSTANCE.seed, newValue -> ModConfig.INSTANCE.seed = newValue)
                        .flag(OptionFlag.ASSET_RELOAD)
                        .controller(LongFieldControllerBuilder::create)
                        .build()
                    )
                    .build()
                )
                .group(OptionGroup.createBuilder()
                    .name(Text.literal("Export"))
                    .collapsed(true)
                    .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Export To Resource Pack"))
                        .binding(false, () -> ModConfig.INSTANCE.exportToResourcePack, newValue -> ModConfig.INSTANCE.exportToResourcePack = newValue)
                        .controller(TickBoxControllerBuilder::create)
                        .build()
                    )
                    .option(Option.<Boolean>createBuilder()
                        .name(Text.literal("Export All Supported Resources"))
                        .binding(false, () -> ModConfig.INSTANCE.exportAll, newValue -> ModConfig.INSTANCE.exportAll = newValue)
                        .controller(TickBoxControllerBuilder::create)
                        .build()
                    )
                    .option(Option.<String>createBuilder()
                        .name(Text.literal("Generated Pack Name"))
                        .binding("generated", () -> ModConfig.INSTANCE.generatedPackName, newValue -> ModConfig.INSTANCE.generatedPackName = newValue)
                        .controller(StringControllerBuilder::create)
                        .build()
                    )
                    .build()
                )
                .build()
            )
            .save(ModConfig::save)
            .build()
            .generateScreen(parent);
    }
}
