plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
    id "com.diffplug.spotless" version "8.+"
    id "com.modrinth.minotaur" version "2.+"
    id "maven-publish"
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        name = "Xander Maven"
        url = "https://maven.isxander.dev/releases"
        content {
            includeGroup "dev.isxander"
            includeGroup "org.quiltmc.parsers"
        }
    }
    maven {
        name = "TerraformersMC Maven"
        url = "https://maven.terraformersmc.com/releases"
        content {
            includeGroup "com.terraformersmc"
        }
    }
    maven { // is this needed?
        url = "https://maven.nucleoid.xyz"
        content {
            includeGroup "eu.pb4"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"
    implementation "dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric"
}

apply from: "https://raw.githubusercontent.com/Tr100000/modding-utils/main/scripts/devlogin.gradle"

spotless {
    format "misc", {
        target "*.gradle", "*.properties", ".gitattributes", ".gitignore"

        trimTrailingWhitespace()
        leadingTabsToSpaces(4)
        endWithNewline()
    }
    java {
        removeUnusedImports()
        trimTrailingWhitespace()
        leadingTabsToSpaces(4)
        endWithNewline()
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "archivesName", project.base.archivesName

    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}" }
    }
}

modrinth {
    projectId = "text-randomizer"
    versionNumber = project.version
    versionName = project.version
    uploadFile = jar
    changelog = rootProject.file("CHANGELOG.md").text
    syncBodyFrom = rootProject.file("README.md").text
}

tasks.modrinth.dependsOn(tasks.modrinthSyncBody)

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}
