# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Mod Properties
mod_version=0.1.0
maven_group=io.github.tr100000
archives_base_name=text_randomizer

# https://fabricmc.net/develop/
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT

modmenu_version=18.0.0-alpha.8
yacl_version=3.9.1+26.1
