mod.id = "text_randomizer"
mod.name = "Text Randomizer"
mod.group = "io.github.tr100000.text_randomizer"
mod.version = "0.2.1"

deps.fabric_loader = "0.19.3"
loomx.loom_version = "1.17-SNAPSHOT"

["1.21.1"]
mod.mc_releases = ["1.21", "1.21.1"]
deps.yacl = "3.8.2+1.21.1"

[fabric."1.21.1"]
mod.mc_compat = ">=1.21 <=1.21.1"
deps.modmenu = "11.0.4"

[neoforge."1.21.1"]
mod.mc_compat = "[1.21, 1.21.1]"
deps.neo_loader = "21.1.244"

["1.21.11"]
mod.mc_releases = ["1.21.11"]
deps.yacl = "3.8.2+1.21.11"

[fabric."1.21.11"]
mod.mc_compat = "1.21.11"
deps.modmenu = "17.0.0"

[neoforge."1.21.11"]
mod.mc_compat = "[1.21.11]"
deps.neo_loader = "21.11.45"

["26.x"]
mod.mc_releases = ["26.1", "26.1.1", "26.1.2", "26w14a", "26.2"]
deps.yacl = "3.9.4+26.2"

[fabric."26.x"]
mod.mc_compat = "^26"
deps.modmenu = "20.0.1"

[neoforge."26.x"]
mod.mc_compat = "[26, 27)"
deps.neo_loader = "26.2.0.37-beta"
